export type Language = "python" | "java" | "c";

export interface Algorithm {
  id: string;
  name: string;
  description: string;
  implementations: Record<Language, string[]>;
}

export const algorithms: Algorithm[] = [
  {
    id: "dfs",
    name: "Depth-First Search",
    description:
      "Graph traversal algorithm that explores as far as possible along each branch before backtracking.",
    implementations: {
      python: [
        "def dfs(graph, node, visited=None):",
        "    if visited is None:",
        "        visited = set()",
        "    visited.add(node)",
        "    for neighbor in graph[node]:",
        "        if neighbor not in visited:",
        "            dfs(graph, neighbor, visited)",
        "    return visited",
      ],
      java: [
        "void dfs(Map<Integer, List<Integer>> graph, int node, Set<Integer> visited) {",
        "    visited.add(node);",
        "    for (int neighbor : graph.get(node)) {",
        "        if (!visited.contains(neighbor)) {",
        "            dfs(graph, neighbor, visited);",
        "        }",
        "    }",
        "}",
      ],
      c: [
        "void dfs(int graph[][MAX], int node, int visited[], int n) {",
        "    visited[node] = 1;",
        "    for (int i = 0; i < n; i++) {",
        "        if (graph[node][i] && !visited[i]) {",
        "            dfs(graph, i, visited, n);",
        "        }",
        "    }",
        "}",
      ],
    },
  },
  {
    id: "bfs",
    name: "Breadth-First Search",
    description:
      "Graph traversal algorithm that explores all neighbors at the present depth before moving to nodes at the next depth level.",
    implementations: {
      python: [
        "def bfs(graph, start):",
        "    visited = set([start])",
        "    queue = [start]",
        "    while queue:",
        "        node = queue.pop(0)",
        "        for neighbor in graph[node]:",
        "            if neighbor not in visited:",
        "                visited.add(neighbor)",
        "                queue.append(neighbor)",
        "    return visited",
      ],
      java: [
        "void bfs(Map<Integer, List<Integer>> graph, int start) {",
        "    Set<Integer> visited = new HashSet<>();",
        "    Queue<Integer> queue = new LinkedList<>();",
        "    visited.add(start);",
        "    queue.add(start);",
        "    while (!queue.isEmpty()) {",
        "        int node = queue.poll();",
        "        for (int neighbor : graph.get(node)) {",
        "            if (!visited.contains(neighbor)) {",
        "                visited.add(neighbor);",
        "                queue.add(neighbor);",
        "            }",
        "        }",
        "    }",
        "}",
      ],
      c: [
        "void bfs(int graph[][MAX], int start, int n) {",
        "    int visited[MAX] = {0};",
        "    int queue[MAX], front = 0, rear = 0;",
        "    visited[start] = 1;",
        "    queue[rear++] = start;",
        "    while (front < rear) {",
        "        int node = queue[front++];",
        "        for (int i = 0; i < n; i++) {",
        "            if (graph[node][i] && !visited[i]) {",
        "                visited[i] = 1;",
        "                queue[rear++] = i;",
        "            }",
        "        }",
        "    }",
        "}",
      ],
    },
  },
  {
    id: "mergesort",
    name: "Merge Sort",
    description:
      "Efficient, stable sorting algorithm using divide-and-conquer strategy.",
    implementations: {
      python: [
        "def merge_sort(arr):",
        "    if len(arr) <= 1:",
        "        return arr",
        "    mid = len(arr) // 2",
        "    left = merge_sort(arr[:mid])",
        "    right = merge_sort(arr[mid:])",
        "    return merge(left, right)",
      ],
      java: [
        "void mergeSort(int[] arr, int left, int right) {",
        "    if (left < right) {",
        "        int mid = (left + right) / 2;",
        "        mergeSort(arr, left, mid);",
        "        mergeSort(arr, mid + 1, right);",
        "        merge(arr, left, mid, right);",
        "    }",
        "}",
      ],
      c: [
        "void mergeSort(int arr[], int left, int right) {",
        "    if (left < right) {",
        "        int mid = left + (right - left) / 2;",
        "        mergeSort(arr, left, mid);",
        "        mergeSort(arr, mid + 1, right);",
        "        merge(arr, left, mid, right);",
        "    }",
        "}",
      ],
    },
  },
  {
    id: "quicksort",
    name: "Quick Sort",
    description:
      "Efficient sorting algorithm using partitioning and divide-and-conquer.",
    implementations: {
      python: [
        "def quicksort(arr):",
        "    if len(arr) <= 1:",
        "        return arr",
        "    pivot = arr[len(arr) // 2]",
        "    left = [x for x in arr if x < pivot]",
        "    middle = [x for x in arr if x == pivot]",
        "    right = [x for x in arr if x > pivot]",
        "    return quicksort(left) + middle + quicksort(right)",
      ],
      java: [
        "void quickSort(int[] arr, int low, int high) {",
        "    if (low < high) {",
        "        int pi = partition(arr, low, high);",
        "        quickSort(arr, low, pi - 1);",
        "        quickSort(arr, pi + 1, high);",
        "    }",
        "}",
      ],
      c: [
        "void quickSort(int arr[], int low, int high) {",
        "    if (low < high) {",
        "        int pi = partition(arr, low, high);",
        "        quickSort(arr, low, pi - 1);",
        "        quickSort(arr, pi + 1, high);",
        "    }",
        "}",
      ],
    },
  },
  {
    id: "dijkstra",
    name: "Dijkstra's Algorithm",
    description: "Finds the shortest path between nodes in a weighted graph.",
    implementations: {
      python: [
        "def dijkstra(graph, start):",
        "    dist = {node: float('inf') for node in graph}",
        "    dist[start] = 0",
        "    pq = [(0, start)]",
        "    while pq:",
        "        d, node = heapq.heappop(pq)",
        "        for neighbor, weight in graph[node]:",
        "            if dist[node] + weight < dist[neighbor]:",
        "                dist[neighbor] = dist[node] + weight",
        "                heapq.heappush(pq, (dist[neighbor], neighbor))",
        "    return dist",
      ],
      java: [
        "void dijkstra(int[][] graph, int src, int n) {",
        "    int[] dist = new int[n];",
        "    boolean[] visited = new boolean[n];",
        "    Arrays.fill(dist, Integer.MAX_VALUE);",
        "    dist[src] = 0;",
        "    for (int i = 0; i < n - 1; i++) {",
        "        int u = minDistance(dist, visited, n);",
        "        visited[u] = true;",
        "        for (int v = 0; v < n; v++) {",
        "            if (!visited[v] && graph[u][v] != 0) {",
        "                if (dist[u] + graph[u][v] < dist[v]) {",
        "                    dist[v] = dist[u] + graph[u][v];",
        "                }",
        "            }",
        "        }",
        "    }",
        "}",
      ],
      c: [
        "void dijkstra(int graph[][MAX], int src, int n) {",
        "    int dist[MAX], visited[MAX] = {0};",
        "    for (int i = 0; i < n; i++) dist[i] = INT_MAX;",
        "    dist[src] = 0;",
        "    for (int i = 0; i < n - 1; i++) {",
        "        int u = minDistance(dist, visited, n);",
        "        visited[u] = 1;",
        "        for (int v = 0; v < n; v++) {",
        "            if (!visited[v] && graph[u][v]) {",
        "                if (dist[u] + graph[u][v] < dist[v]) {",
        "                    dist[v] = dist[u] + graph[u][v];",
        "                }",
        "            }",
        "        }",
        "    }",
        "}",
      ],
    },
  },
];

export const languages: { id: Language; name: string }[] = [
  { id: "python", name: "Python" },
  { id: "java", name: "Java" },
  { id: "c", name: "C" },
];
